# Generated by Django 3.2.4 on 2021-06-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
