# Generated by Django 3.2.4 on 2021-06-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0012_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
