# Generated by Django 3.2.4 on 2021-06-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_auto_20210620_1912'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
