# Generated by Django 3.2.4 on 2021-07-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0021_remove_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(default='fkd;fsdf', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.TextField(max_length=4000),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
