# Generated by Django 3.2.4 on 2021-07-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0023_alter_order_data_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='data_ordered',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default='1111-11-11'),
        ),
    ]
