# Generated by Django 3.2.4 on 2021-07-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0025_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tel',
            field=models.CharField(default=88005553535, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
